### ISSUE TITLE
What version is this currently supported for?

### ISSUE THREAD

**Issue by caoqt1** [sekwah41/SekC-Physics#31]
Question for sekwah, what version is this currently supported for as i am going to compile this but i have no idea what version it is currently built for, also is it client side still as i am looking forward to using this on a server.

**Comment by sekwah41** [comment]
Once I've got the Naruto mod updated (it almost is) I need to rewrite this mod.

Forge works for. 1.12 and fabric works for 1.14.

I'll be happy to generally discuss the mod more on the discord if you have any more questions https://discord.sekwah.com/

**Comment by caoqt1** [comment]
Thanks, will join the discord server, oh and by the way the last time i used this mod rag dolls could turn all their body parts 360 so in some cases the head would be twisted inside the torso or the legs would be folded, are you going to fix that or is it already fixed?

**Comment by sekwah41** [comment]
I need to add some new physics which will add angle constraints. Its not done yet though yea :/ I know how I'm going to do it but yea I was busy with uni back when this mod was initially released.

**Comment by sekwah41** [comment]
Working slowly on a 1.19 version :)

**Comment by James103** [comment]
> Working slowly on a 1.19 version :)

1. Modloader: Forge, Fabric or both?
2. Which 1.19 point releases will be supported? (e.g. 1.19.2 and 1.19.4)

**Comment by sekwah41** [comment]
Preferably all 1.19 versions like with SekCLib though I will be targeting the latest. Also forge for now though I will explore making my mods on both, it's just that I use a method to load my mods all together at once in dev that only works with forge.

Also I found that there was far more use of my mod despite I basically abandoned the forge version in 1.12 on forge by a long shot.

**Comment by sekwah41** [comment]
I will be using the mojang mappings so it should be relatively easy to port changes I make across to the other version, though I need to look at or work on making SekCLib also on fabric (not that itll be needed immediately for this at least). Ill probably do a port for fun every now and then just to gauge how large the forge vs fabric userbase is too.
