### ISSUE TITLE
Crash w/ Tinker Tool Leveling Mod

### ISSUE THREAD

**Issue by WenXin20** [sekwah41/SekC-Physics#9]
**Describe the bug**
The game crashed after I killed a zombie. The weapon used was not a tconstruct weapon, nor did I have any other tconstruct tools in my inventory or nearby. The zombie ragdoll hadn't appeared when it crashed.
[**Crash Log**](https://gist.github.com/WenXin20/8ffed53ea4ad3753338be555e4300511)

**To Reproduce**
Steps to reproduce the behavior if you have found out how to trigger it:
1. Spawn Zombie
2. Kill Zombie with any tool/weapon

**Expected behavior**
For the zombie ragdoll to appear without a crash occuring.

**Screenshots**
None available

**Mod Versions**
- Sekc Physics v0.1.0
- [Tinker Tool Leveling](https://minecraft.curseforge.com/projects/tinkers-tool-leveling) v1.1.0

**Mod Branch (Modding system used)**
- [x] Forge v14.23.5.2796-1.12.2
- [ ] Fabric

**Comment by sekwah41** [comment]
I thought this was more straightforward such as the entity being killed right there and then but it seems to have the crash from inside SekCPhysics which is more confusing. Ill take a look at it at lunch if I have the time. Thanks for linking the mod.

**Comment by sekwah41** [comment]
Wait by crash do you mean an error in the console or the game shutting down?

Edit: Sorry saw crash log that does say about it fully crashing its just I am getting the error but its just not spawning the ragdoll.

**Comment by WenXin20** [comment]
Yeah, the game froze and then crashed.

**Comment by sekwah41** [comment]
Sorry for the delay. The changes I am making in fabric when ported back should fix this issue

**Comment by sekwah41** [comment]
I didnt expect to really end up not doing modding for a while. As I am currently updating to 1.16 will be closing this for now as I am no longer working on older versions. Hopefully, this isn't an issue in the future versions.
